name: deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow job to create Github Release

    steps:

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Pre-requisites
        run: python -m pip install build python-semantic-release

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # semantic-release needs access to all previous commits

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release -v version
