name: deploy

on:
  push:
    branches:
      - main

jobs:
  test-release:
    if: github.events.commits[0].author.name == 'semantic-release'

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: testpypi
      url: https://pypi.org/p/testing-fixtures

    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Pre-requisites
        run: python -m pip install build

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: pyproject-build

      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
