name: deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.event.commits[0].author.name != 'semantic-release'

    runs-on: ubuntu-latest

    steps:

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Pre-requisites
        run: python -m pip install build python-semantic-release

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # semantic-release needs access to all previous commits
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Semantic Release
        run: semantic-release -vv version

      - name: Debug
        run: echo "Hello, World!"
