name: deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.event.commits[0].author.name != 'semantic-release'

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Pre-requisites
        run: python -m pip install build python-semantic-release

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # semantic-release needs access to all previous commits
          token: ${{ secrets.PAT }}

      - name: Semantic Release Version
        run: semantic-release version
        env:
          GH_TOKEN: ${{ secrets.PAT }}
