name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install semnatic-release
        run: python -m pip install python-semantic-release

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # env var expected by semantic-release
        run: |  # configure identity for semantic-release commit
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
